sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - env: CXX=g++-6 CC=gcc-6
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6

    - env: CXX=g++-7 CC=gcc-7
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7

    - env: CXX=clang++-3.9 CC=clang-3.9
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9

    - env: CXX=clang++-4.0 CC=clang-4.0
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0

    - env: CXX=clang++-5.0 CC=clang-5.0
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0

before_install:
  - eval "${MATRIX_EVAL}"
  - echo ${CC}
  - echo ${CXX}
  - ${CXX} --version

install:
  - source .travis/cuda_install.sh

  - echo "installing cmake"
  - source .travis/cmake_install.sh
  - ~/cmake-${CMAKE_VER}/bin/cmake --version

  - echo "installing googletest"
  - source .travis/gtest_install.sh

script:
  - ~/cmake-${CMAKE_VER}/bin/cmake -G "Unix Makefiles"
  - make install
  - make test
