sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
          - gcc-6
      env:
        - MATRIX_EVAL="CXX=g++-6 && CC=gcc-6"

    - os: linux
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
          - gcc-7
      env:
        - MATRIX_EVAL="CXX=g++-7 && CC=gcc-7"

    - os: linux
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-3.9
        packages:
          - clang-3.9
      env: 
        - MATRIX_EVAL="CXX=clang++-3.9 && CC=clang-3.9"

    - os: linux
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-4.0
        packages:
          - clang-4.0
      env: 
        - MATRIX_EVAL="CXX=clang++-4.0 && CC=clang-4.0"

    - os: linux
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
        packages:
          - clang-5.0
      env:
        - MATRIX_EVAL="CXX=clang++-5.0 && CC=clang-5.0"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - source .travis/cuda_install.sh

  - echo "installing cmake"
  - source .travis/cmake_install.sh

  - echo "installing googletest"
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - ~/cmake-${CMAKE_VER}/bin/cmake -G "Unix Makefiles"
  - sudo make install
  - cd ../

  - echo ${CC}
  - echo ${CXX}
  - ${CXX} --version
  - ~/cmake-${CMAKE_VER}/bin/cmake --version

script:
  - cd ~/Red-Portal/mgcpp
  - ~/cmake-${CMAKE_VER}/bin/cmake -G "Unix Makefiles"
  - make install
  - make test
